// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinqLNEmXRbH5VsRNtX0woib16IDTN9Bw',
    appId: '1:870939065953:web:6878410adbd8d0d84ef420',
    messagingSenderId: '870939065953',
    projectId: 'circlo-e37f2',
    authDomain: 'circlo-e37f2.firebaseapp.com',
    storageBucket: 'circlo-e37f2.firebasestorage.app',
    measurementId: 'G-JBSH6K34YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0Vi-dH7VqpRQvurkk67EQbGuUomqRa4',
    appId: '1:870939065953:android:312fd509e536e0d94ef420',
    messagingSenderId: '870939065953',
    projectId: 'circlo-e37f2',
    storageBucket: 'circlo-e37f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXKHhp4kxApwJ2wCKQXIQegpXfq_67BQ8',
    appId: '1:870939065953:ios:142219e2757fcad74ef420',
    messagingSenderId: '870939065953',
    projectId: 'circlo-e37f2',
    storageBucket: 'circlo-e37f2.firebasestorage.app',
    iosBundleId: 'com.example.circlo',
  );
}
